### ISSUE TITLE
cchhs fails with airtable pipeline

### ISSUE THREAD

**Issue by eads** [City-Bureau/documenters-aggregator#133]
```
2017-10-05 21:54:01 [scrapy.core.scraper] ERROR: Error processing {'description': 'http://www.cookcountyhhs.org/wp-content/uploads/2017/08/08-17-17-Managed-Care-Agenda.pdf', 'classification': 'Not classified', 'start_time': '2017-08-17T10:30:00-05:00', 'location': {'url': '', 'name': '1900 W. Polk, Second Floor Conference Room, Chicago, Illinois', 'coordinates': None}, '_type': 'event', 'name': 'Managed Care Committee Meetings', 'end_time': 'See description', 'all_day': False, 'status': 'passed', 'id': 'ManagedCareCommitteeMeetings2017-08-17T10:30:00-05:00'}
Traceback (most recent call last):
  File "/Users/DE-Admin/.virtualenvs/documenters-aggregator/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/DE-Admin/Code/documenters-aggregator/documenters_aggregator/pipelines.py", line 64, in process_item
    new_item['end_time_formatted'] = self._transform_date(new_item['end_time'])
  File "/Users/DE-Admin/Code/documenters-aggregator/documenters_aggregator/pipelines.py", line 95, in _transform_date
    dt = dateutil.parser.parse(timestring)
  File "/Users/DE-Admin/.virtualenvs/documenters-aggregator/lib/python3.6/site-packages/dateutil/parser.py", line 1182, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/Users/DE-Admin/.virtualenvs/documenters-aggregator/lib/python3.6/site-packages/dateutil/parser.py", line 559, in parse
    raise ValueError("Unknown string format")
```

**Comment by r-wei** [comment]
I can fix this and put the dates for all the scrapers in the same format. There are 2 formats right now.

1) dates in this format with the number of hours offset from utc at the end: 2017-01-01T12:00:00-05:00
2) dates in utc (2017-01-01T07:00:00Z) with an extra field timezone="America/Chicago"

@eads is there a preference for which one?

**Comment by r-wei** [comment]
@eads , do you have a preference for 1 vs 2 here?

**Comment by eads** [comment]
#1 sounds good!
