### ISSUE TITLE
chi_infra spider is broken

### ISSUE THREAD

**Issue by r-wei** [City-Bureau/documenters-aggregator#202]
Here is the error from ```scrapy crawl chi_infra```

```
[scrapy.core.scraper] ERROR: Spider error processing <GET http://chicagoinfrastructure.org/public-records/scheduled-meetings/> (referer: None)
Traceback (most recent call last):
  File "/Users/aweia/.virtualenvs/documenters-aggregator/lib/python3.6/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/Users/aweia/.virtualenvs/documenters-aggregator/lib/python3.6/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/Users/aweia/.virtualenvs/documenters-aggregator/lib/python3.6/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/Users/aweia/.virtualenvs/documenters-aggregator/lib/python3.6/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/Users/aweia/.virtualenvs/documenters-aggregator/lib/python3.6/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/Users/aweia/projects/documenters-aggregator/documenters_aggregator/spiders/chi_infra.py", line 30, in parse
    self.year = int(year_match.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
```

Working on this issue would familiarize you with our spider infrastructure and working with scrapy.

**Comment by r-wei** [comment]
resolved by #223
